spring.application.name=sanity-app

# Azure SQL Database Configuration
spring.datasource.url=jdbc:sqlserver://carlosedusql.database.windows.net:1433;databaseName=carlosdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30
spring.datasource.username=carlosadmin@carlosedusql
spring.datasource.password=Admin1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# JWT Configuration
jwt.secret=MiClaveSecretaSuperSeguraParaJWTDebeSerMuyLarga123456789
jwt.expiration=86400000
