spring.application.name=sanity-users
server.port=8081

# Azure SQL Database Configuration
spring.datasource.url=jdbc:sqlserver://carlosedusql.database.windows.net:1433;databaseName=carlosdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30
spring.datasource.username=carlosadmin@carlosedusql
spring.datasource.password=Admin1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# JWT Configuration
jwt.secret=MiClaveSecretaSuperSeguraParaJWTDebeSerMuyLarga123456789
jwt.expiration=86400000

# ID DE GOOGLE PARA INICIO DE SESION
google.client-id=TU_GOOGLE_CLIENT_ID.apps.googleusercontent.com

# Google Cloud Storage
gcs.bucket-name=115305318075-us-central1-blueprint-config
gcs.credentials-path=classpath:gcs-credentials.json

# Multipart file upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB